defaultBranch: 'develop'
branchName: '${issue.number}-${issue.title[0,64],}'
gitSafeReplacementChar: '-'
branches:
- label: feature
  name: develop
  prefix: features/
- label: hotfix
  name: main
  prefix: hotfix/
